---
output: svg, debug
expected-description: (Timing Diagram)
---
@startuml
time-axis unit "ns"
robust "Signal" as S
concise "Bus" as B

@0
S is Idle
B is Free
@100
S is Busy
@200
B is Data
@300
S is Idle
@enduml
